name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Convert repository owner to lowercase
        id: repoowner
        run: echo "::set-output name=lowercase::$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')"

      - name: Get repository name
        id: reponame
        run: echo "::set-output name=name::$(echo ${{ github.repository }} | cut -d'/' -f2)"

      - name: Add source label to Dockerfile
        run: |
          echo -e $'\nLABEL org.opencontainers.image.source=https://github.com/${{ steps.repoowner.outputs.lowercase }}/${{ steps.reponame.outputs.name }}' >> Dockerfile

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.repoowner.outputs.lowercase }}/${{ steps.reponame.outputs.name }}:latest
            ghcr.io/${{ steps.repoowner.outputs.lowercase }}/${{ steps.reponame.outputs.name }}:${{ github.sha }}